# Generated by Django 3.2.16 on 2023-01-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytype',
            options={'verbose_name': 'نوع المخزن', 'verbose_name_plural': 'نوع المخازن'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
